---
version: 0.2
phases:
  install:
    commads:
      - echo Installing maven..
      - apt-get update -y && apt-get install -y maven
      - export START_TIME=$( date +%s )
  pre_build:
    commands:
      - echo Exporting PROJECT_VERSION from pom.xml
      - export $(printf 'PROJECT_VERSION=${project.version}' | mvn help:evaluate | grep ^PROJECT_VERSION=)
  build:
    commands:
      - echo Initiating build sequence, sounds cool :-)
      - mvn clean verify
  post_build:
    commands:
      - echo Build completed in $(( $( date +%s ) - START_TIME ))

artifacts:
  files:
    - target/Library-$PROJECT_VERSION.war
