---
version: 0.2
phases:
  install:
    - echo Installing maven..
    - apt-get update -y && apt-get install -y maven
    - export START_TIME=$( date +%s )
  pre_build:
    - echo Exporting PROJECT_VERSION from pom.xml
    - export $(printf 'PROJECT_VERSION=${project.version}' | mvn help:evaluate | grep ^PROJECT_VERSION=)
  build:
    - echo Initiating build sequence, sounds cool :-)
    - mvn clean verify
  postbuild:
    - echo Build completed in $(( $( date +%s ) - START_TIME ))

artifacts:
  files:
    - target/Library-$PROJECT_VERSION.war
