---
version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging into ECR
      - export START_TIME=$( date +%s )
      - echo STARTING TIME = $START_TIME
      - echo Exporting PROJECT_VERSION from pom.xml
      - export $(printf 'PROJECT_VERSION=${project.version}' | mvn help:evaluate | grep ^PROJECT_VERSION=)
  build:
    commands:
      - echo Initiating maven build sequence
      - mvn clean verify
  post_build:
    commands:
      - echo Build completed in $(( $( date +%s ) - START_TIME ))s

artifacts:
  files:
    - target/Library-$PROJECT_VERSION.war
    - docker/buildspec.yml
    - docker/Dockerfile
  discard-paths: yes

