---
version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging into ECR
      - $(aws ecr get-login --region eu-central-1)
      - export START_TIME=$( date +%s )
      - echo STARTING TIME = $START_TIME
      - export PROJECT_VERSION=$(ls Library-*.war | sed -e "s/^Library-//; s/.war$//")
  build:
    commands:
      - echo Building docker image
      - docker build -f Dockerfile -t library:$PROJECT_VERSION .
      - docker tag library:$PROJECT_VERSION 997272741948.dkr.ecr.eu-central-1.amazonaws.com/library:$PROJECT_VERSION
  post_build:
    commands:
      - echo Build completed in $(( $( date +%s ) - START_TIME ))s
      - echo Pushing docker image into ECR
      - docker push 997272741948.dkr.ecr.eu-central-1.amazonaws.com/library:$PROJECT_VERSION
