---
version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging into ECR
      - $(aws ecr get-login --region eu-central-1)
      - export START_TIME=$( date +%s )
      - echo STARTING TIME = $START_TIME
      - echo Exporting PROJECT_VERSION from pom.xml
      - export PROJECT_VERSION=$(python -c "import xml.etree.ElementTree as ET; print(ET.parse(open('pom.xml')).getroot().find('{http://maven.apache.org/POM/4.0.0}version').text)")
  build:
    commands:
      - echo Building docker image
      - docker build -f docker/Dockerfile.build -t library:$PROJECT_VERSION .
      - docker tag library:$PROJECT_VERSION 997272741948.dkr.ecr.eu-central-1.amazonaws.com/library:$PROJECT_VERSION
  post_build:
    commands:
      - echo Build completed in $(( $( date +%s ) - START_TIME ))s
      - echo Pushing docker image into ECR
      - docker push 997272741948.dkr.ecr.eu-central-1.amazonaws.com/library:$PROJECT_VERSION
