---
version: 0.2
phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --storage-driver=overlay&
      - timeout -t 15 sh -c "until docker info; do echo .; sleep 1; done"    
  pre_build:
    commands:
      - echo Logging into ECR
      - $(aws ecr get-login --region eu-central-1 --no-include-email)
      - export START_TIME=$( date +%s )
      - echo STARTING TIME = $START_TIME
      - echo Exporting PROJECT_VERSION from pom.xml
      - export PROJECT_VERSION=$(xmlstarlet sel -t -v /_:project/_:version pom.xml)
  build:
    commands:
      - echo Building docker image
      - docker build -f docker/Dockerfile.build -t library:$PROJECT_VERSION .
      - docker tag library:$PROJECT_VERSION 997272741948.dkr.ecr.eu-central-1.amazonaws.com/library:$PROJECT_VERSION
  post_build:
    commands:
      - echo Build completed in $(( $( date +%s ) - START_TIME ))s
      - echo Pushing docker image into ECR
      - docker push 997272741948.dkr.ecr.eu-central-1.amazonaws.com/library:$PROJECT_VERSION
